### ISSUE TITLE
Recent versions of `vue-tsc` show "declared but never read" errors (variables used in styles)

### ISSUE THREAD

**Issue by glen-84** [johnsoncodehk/volar#1093]
With the latest versions of `vue-tsc`, I'm seeing errors like this:

```ts
src/app/core/layouts/default.vue:302:7 - error TS6133: 'sectionImages' is declared but its value is never read.

302 const sectionImages = computed(() => {
          ~~~~~~~~~~~~~
```

The styles:

```scss
.content {
    background-image: v-bind("sectionImages.logo.image"), v-bind("sectionImages.header.image");
}
```
