### ISSUE TITLE
Feature request: option to hide split editing action icon

### ISSUE THREAD

**Issue by zmwangx** [johnsoncodehk/volar#170]
I don't use the split editing feature, so unfortunately the icon adds clutter to the UI. It also looks pretty jarring among other monochrome icons:

![image](https://user-images.githubusercontent.com/4149852/117286372-b254d500-ae9b-11eb-9ac1-c50d33934b19.png)

I wonder if an option can be added to disable it?

If not, this issue could double as a place to share my current solution: I use the [Custom CSS and JS Loader](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css) extension to inject the following CSS:

```css
.action-label[title="Split <script>, <template>, <style> Editors"] {
  display: none !important;
}
```

Do note that the extension works by modifying VS Code files (what VS Code itself considers corruption), so it's really not a great solution.
