### ISSUE TITLE
Slow suggestions

### ISSUE THREAD

**Issue by Zenthae** [johnsoncodehk/volar#502]
Using Volar, auto completion become unusable because it can takes seconds to display the suggestion, when, most of the time you already have finished typing. I've seen #455 but i don't know if it's linked, i tested with every extension disabled other than volar `0.27.21`

**Comment by johnsoncodehk** [comment]
Please try to provide repro case, see https://github.com/johnsoncodehk/volar/issues/507#issuecomment-922251114.

**Comment by Zenthae** [comment]
there is no need of repro case, i just tested with default volar-starter and it's behaving the same way, suggestion is slow to display/load

**Comment by johnsoncodehk** [comment]
Have you try disable other extensions? And please also make sure `volar.lowPowerMode` is disabled.

Please provide your VSCode info by `Help: About` command, and profiling record: https://github.com/johnsoncodehk/volar/discussions/413

**Comment by Zenthae** [comment]
>  i tested with every extension disabled other than volar 0.27.21

VSCode Info : 
```yaml
Version: 1.60.1 (system setup)
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:07:10.714Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```

`volar.lowPowerMode` is set to `false`

little example of what i'm trying to say, and btw, the part before displaying `Loading...` is also about 0.5 sec long

![p9b4k6kkNd](https://user-images.githubusercontent.com/32647899/133933493-345b9b4f-0112-4495-9b1d-0888a9724063.gif)
