### ISSUE TITLE
Not Support css/less relative image path

### ISSUE THREAD

**Issue by bobby169** [johnsoncodehk/volar#759]
```css
#nav {
  /* Support */
  background: url(./assets/logo.png);

  /* Not Support */
  background: url(assets/logo.png);
}
```
