### ISSUE TITLE
Complex scss highlighting anomalies

### ISSUE THREAD

**Issue by gadfly3173** [johnsoncodehk/volar#789]
I have some scss in SFC like this:
```scss
:deep(.el-scrollbar) {
  .reserve-drawer {
    padding: 0 20px;
    .create-btn {
      margin-bottom: 10px;
    }
  }
}
.reserve-edit-form {
  :deep(.el-form-item__content) {
    .el-input-number--mini {
      width: 80px;
    }
  }
}
```
it is rendered like this, seems not correct. How can I fix it?
![image](https://user-images.githubusercontent.com/28685179/146140945-9fe23cac-89ce-4271-a868-8c0ee2c96774.png)
